### ISSUE TITLE
DOC: link to homepage on agstack/ org account

### ISSUE THREAD

**Issue by westurner** [agstack/governance#2]
- [x] add link to https://agstack.org on https://github.com/agstack

**Comment by vmbrasseur** [comment]
Done!

**Comment by westurner** [comment]
Thanks

**Comment by westurner** [comment]
Also, it's possible to create a short README for an org account that
displays above the list of repos.
https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile

The projects list might be good content for an org README:
https://agstack.org/projects/

**Comment by vmbrasseur** [comment]
Yes, I know. There are other fires to put out first, though. ;-)

**Comment by westurner** [comment]
- e.g. conda-forge 's org readme looks more like an awesome list with a short description of each; but who would maintain the favored toplist in the README.
- there's probably a DRY solution
  - org account description:
    https://github.com/agstack
    - [x] #2
  - org account readme
    - https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile
    - https://agstack.org/projects/ has an architecture diagram:
      - mermaidJS diagrams might or might not work in org account readmes: https://github.blog/developer-skills/github/include-diagrams-markdown-files-mermaid/
    - https://github.com/agstack/.github /README.md
    - example org README: https://github.com/conda-forge
  - repo list:
    https://github.com/orgs/agstack/repositories
  - org/repos list HTTP API: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories
  - "pinned repos"
    - [Pinning repositories to your organization's profile](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#pinning-repositories-to-your-organizations-profile)

**Comment by vmbrasseur** [comment]
Yes, as I said, I'm familiar with org-level READMEs and will get to it in time.

If you would like to suggest one for AgStack, please open a separate issue. Thanks.
